default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: weather_information_development

test:
  <<: *default
  database: weather_information_test

production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
  username: <%= ENV['PG_USERNAME'] %>
  password: <%= ENV['PG_PASSWORD'] %>
  host: /cloudsql/<%= ENV['PG_CONNECTION_NAME'] %>
  database: weather_information_production
